-- WARNING: This schema is for context only and is not meant to be run.
-- Table order and constraints may not be valid for execution.

CREATE TABLE public.actual_production (
  id bigint NOT NULL DEFAULT nextval('actual_production_id_seq'::regclass),
  Timestamp timestamp with time zone,
  Job Card No. text,
  FIRM Name text,
  Date Of Production date,
  Name Of Supervisor text,
  Product Name text,
  Quantity Of FG numeric,
  Serial Number text,
  Raw Material Name 1 text,
  Quantity Of Raw Material 1 numeric,
  Raw Material Name 2 text,
  Quantity Of Raw Material 2 numeric,
  Raw Material Name 3 text,
  Quantity Of Raw Material 3 numeric,
  Raw Material Name 4 text,
  Quantity Of Raw Material 4 numeric,
  Raw Material Name 5 text,
  Quantity Of Raw Material 5 numeric,
  Raw Material Name 6 text,
  Quantity Of Raw Material 6 numeric,
  Raw Material Name 7 text,
  Quantity Of Raw Material 7 numeric,
  Raw Material Name 8 text,
  Quantity Of Raw Material 8 numeric,
  Raw Material Name 9 text,
  Quantity Of Raw Material 9 numeric,
  Raw Material Name 10 text,
  Quantity Of Raw Material 10 numeric,
  Raw Material Name 11 text,
  Quantity Of Raw Material 11 numeric,
  Raw Material Name 12 text,
  Quantity Of Raw Material 12 numeric,
  Raw Material Name 13 text,
  Quantity Of Raw Material 13 numeric,
  Raw Material Name 14 text,
  Quantity Of Raw Material 14 numeric,
  Raw Material Name 15 text,
  Quantity Of Raw Material 15 numeric,
  Raw Material Name 16 text,
  Quantity Of Raw Material 16 numeric,
  Raw Material Name 17 text,
  Quantity Of Raw Material 17 numeric,
  Raw Material Name 18 text,
  Quantity Of Raw Material 18 numeric,
  Raw Material Name 19 text,
  Quantity Of Raw Material 19 numeric,
  Raw Material Name 20 text,
  Quantity Of Raw Material 20 numeric,
  Machine Running hour numeric,
  Remarks1 text,
  PP BAG USED numeric,
  PP BAG TO BE USED numeric,
  Party Name text,
  PP Bag (Small) numeric,
  Costing Amount numeric,
  Color Condition text,
  Order No. text,
  Planned1 date,
  Actual1 date,
  Time Delay1 integer,
  Planned2 date,
  Actual2 date,
  Time Delay2 integer,
  Planned3 date,
  Actual3 date,
  Time Delay3 integer,
  Planned4 date,
  Actual4 date,
  Remarks2 text,
  Planned5 date,
  Actual5 date,
  Remarks3 text,
  Planned6 date,
  Actual6 date,
  Remarks4 text,
  Status text,
  Qty numeric,
  Remarks text,
  CONSTRAINT actual_production_pkey PRIMARY KEY (id)
);
CREATE TABLE public.costing_response (
  id bigint NOT NULL DEFAULT nextval('costing_response_id_seq'::regclass),
  TIMESTAMP timestamp with time zone DEFAULT now(),
  Composition No. text,
  Order No. text,
  product name text,
  VARIABLE COST numeric,
  Manufacturing Cost numeric,
  Interest (days) integer,
  Interest Cost numeric,
  Transporting (FOR) numeric,
  SELLING PRICE numeric,
  GP %AGE numeric,
  alumina numeric,
  iron numeric,
  BD numeric,
  AP numeric,
  RM1 text,
  RM2 text,
  RM3 text,
  RM4 text,
  RM5 text,
  RM6 text,
  RM7 text,
  RM8 text,
  RM9 text,
  RM10 text,
  RM11 text,
  RM12 text,
  RM13 text,
  RM14 text,
  RM15 text,
  RM16 text,
  RM17 text,
  RM18 text,
  RM19 text,
  RM20 text,
  QTY1 numeric,
  QTY2 numeric,
  QTY3 numeric,
  QTY4 numeric,
  QTY5 numeric,
  QTY6 numeric,
  QTY7 numeric,
  QTY8 numeric,
  QTY9 numeric,
  QTY10 numeric,
  QTY11 numeric,
  QTY12 numeric,
  QTY13 numeric,
  QTY14 numeric,
  QTY15 numeric,
  QTY16 numeric,
  QTY17 numeric,
  QTY18 numeric,
  QTY19 numeric,
  QTY20 numeric,
  Planned 1 date,
  Actual 2 date,
  Time Delay 1 integer,
  Alumina Percentage % numeric,
  Iron Percentage % numeric,
  Status text,
  Planned 2 date,
  Actual 3 date,
  Remarks text,
  CONSTRAINT costing_response_pkey PRIMARY KEY (id)
);
CREATE TABLE public.crushing_actual (
  id bigint NOT NULL DEFAULT nextval('crushing_actual_id_seq'::regclass),
  Timestamp timestamp with time zone,
  Date Of Production date,
  Crushing Product Name text,
  Qty Of Crushing Product numeric,
  Processing Cost numeric,
  Finished Goods Name 1 text,
  Qty 1 numeric,
  Finished Goods Name 2 text,
  Qty 2 numeric,
  Finished Goods Name 3 text,
  Qty 3 numeric,
  Finished Goods Name 4 text,
  Qty 4 numeric,
  Starting Reading Photo text,
  Ending Reading Photo text,
  Remarks text,
  Machine Running Hour numeric,
  CONSTRAINT crushing_actual_pkey PRIMARY KEY (id)
);
CREATE TABLE public.crushing_items_name (
  id bigint NOT NULL DEFAULT nextval('crushing_items_name_id_seq'::regclass),
  Crushing Product Name text,
  Finished Goods Name 1 text,
  Finished Goods Name 2 text,
  Finished Goods Name 3 text,
  Finished Goods Name 4 text,
  Name Of Semi Finished Good text,
  Name Of Raw Material text,
  Add Item In Last Column text,
  Timestamp timestamp with time zone,
  CONSTRAINT crushing_items_name_pkey PRIMARY KEY (id)
);
CREATE TABLE public.jobcards (
  id bigint NOT NULL DEFAULT nextval('jobcards_id_seq'::regclass),
  Timestamp timestamp with time zone DEFAULT (now() AT TIME ZONE 'utc'::text),
  JC-Job Card Number text,
  Firm Name text,
  Supervisor Name text,
  Delivery Order No. text,
  Party Name text,
  Product Name text,
  Quantity numeric,
  Date Of Production date,
  Shift text,
  Notes text,
  Total Made numeric,
  Pending numeric,
  Status text,
  Planned 1 date,
  Actual 1 date,
  Time Delay 1 integer,
  Planned 2 date,
  Actual 2 date,
  Time Delay 2 integer,
  Status 2 text,
  Date Of Test 1 date,
  WC Percentage % numeric,
  Tested By 1 text,
  Initial Setting Time text,
  Flow Of Material text,
  Final Setting Time text,
  What To Be Mixed text,
  Sieve Analysis text,
  Planned 3 date,
  Actual 3 date,
  Time Delay 3 integer,
  Status 3 text,
  Tested By 2 text,
  Date Of Test 2 date,
  BD At 110C numeric,
  CCS At 100C numeric,
  BD At 1100C numeric,
  CCS At 1100C numeric,
  PLC At 1100C numeric,
  Planned 4 date,
  Actual 4 date,
  Time Delay 4 integer,
  Status 4 text,
  Alumina % numeric,
  Iron % numeric,
  Silica % numeric,
  Calcium % numeric,
  Tested By 3 text,
  CONSTRAINT jobcards_pkey PRIMARY KEY (id)
);
CREATE TABLE public.kyc (
  id bigint NOT NULL DEFAULT nextval('kyc_id_seq'::regclass),
  Product name text,
  Alumina numeric,
  Iron numeric,
  Price numeric,
  Bd numeric,
  Ap numeric,
  ALBD numeric,
  Rate Per Alumina numeric,
  CONSTRAINT kyc_pkey PRIMARY KEY (id)
);
CREATE TABLE public.login (
  id bigint NOT NULL DEFAULT nextval('login_id_seq'::regclass),
  User name text,
  ID text UNIQUE,
  Pass text,
  Role text,
  Pages text,
  CONSTRAINT login_pkey PRIMARY KEY (id)
);
CREATE TABLE public.master (
  id bigint NOT NULL DEFAULT nextval('master_id_seq'::regclass),
  Priority text,
  Supervisor Name text,
  Shift text,
  Test Status text,
  Tested by text,
  Status text,
  Firm Name text,
  Material Name text,
  Flow Of Material text,
  SF Supervisor Name text,
  Name Of Raw Material text,
  Finished Goods Name text,
  Crushing Product Name text,
  CONSTRAINT master_pkey PRIMARY KEY (id)
);
CREATE TABLE public.orders (
  id bigint NOT NULL DEFAULT nextval('orders_id_seq'::regclass),
  Firm Name text,
  Party Name text,
  Order No. text,
  Product Name text,
  Timestamp timestamp with time zone,
  CONSTRAINT orders_pkey PRIMARY KEY (id)
);
CREATE TABLE public.production (
  id bigint NOT NULL DEFAULT nextval('production_id_seq'::regclass),
  Timestamp timestamp with time zone DEFAULT (now() AT TIME ZONE 'utc'::text),
  Delivery Order No. text,
  Firm Name text,
  Party Name text,
  Product Name text,
  Order Quantity numeric,
  Expected Delivery Date date,
  Priority text,
  Note text,
  Crm Name text,
  Order Cancel boolean DEFAULT false,
  Actual Production Planned numeric,
  Actual Production Done numeric,
  Stock Transfered numeric,
  Quantity Delivered numeric,
  Quantity In Stock numeric,
  Planning Pending numeric,
  Production Pending numeric,
  Status text,
  Date Of Complete Planning date,
  Planned 1 date,
  Actual 1 date,
  Delay 1 integer,
  Planned2 date,
  Actual2 date,
  Delay 2 integer,
  Reason text,
  CONSTRAINT production_pkey PRIMARY KEY (id)
);
CREATE TABLE public.semi_actual (
  id bigint NOT NULL DEFAULT nextval('semi_actual_id_seq'::regclass),
  Timestamp timestamp with time zone,
  Semi Finished Job Card No. text,
  Supervisor Name text,
  Date Of Production date,
  Product Name text,
  Qty Of Semi Finished Good numeric,
  Raw Material Name 1 text,
  Quantity Of Raw Material 1 numeric,
  Raw Material Name 2 text,
  Quantity Of Raw Material 2 numeric,
  Raw Material Name 3 text,
  Quantity Of Raw Material 3 numeric,
  Raw Material Name 4 text,
  Quantity Of Raw Material 4 numeric,
  Raw Material Name 5 text,
  Quantity Of Raw Material 5 numeric,
  Is Any End Product boolean DEFAULT false,
  End Product Name text,
  End Product Qty numeric,
  Narration text,
  S No. text,
  Starting Reading numeric,
  Starting Reading Photo text,
  Ending Reading numeric,
  Ending Reading Photo text,
  Machine Running hour numeric,
  Machine Running numeric,
  Semi Finished Production No. text,
  Planned1 date,
  Actual1 date,
  Time Delay1 integer,
  Status text,
  Actual Qty1 numeric,
  Planned2 date,
  Actual2 date,
  Time Delay2 integer,
  Status1 text,
  Final Qty numeric,
  CONSTRAINT semi_actual_pkey PRIMARY KEY (id)
);
CREATE TABLE public.semi_job_card (
  id bigint NOT NULL DEFAULT nextval('semi_job_card_id_seq'::regclass),
  Timestamp timestamp with time zone,
  SJC-Sr No. text,
  Semi Finished Production No. text,
  Supervisor Name text,
  Product Name text,
  Qty numeric,
  Date Of Production date,
  Actual Made numeric,
  Pending numeric,
  Status text,
  Planned date,
  Actual date,
  Time Delay integer,
  CONSTRAINT semi_job_card_pkey PRIMARY KEY (id)
);
CREATE TABLE public.semi_production (
  id bigint NOT NULL DEFAULT nextval('semi_production_id_seq'::regclass),
  Timestamp timestamp with time zone,
  SF-Sr No. text,
  Name Of Semi Finished Good text,
  Qty numeric,
  Notes text,
  Total Planned numeric,
  Total Made numeric,
  Pending numeric,
  Cancel Order boolean DEFAULT false,
  Status text,
  Planned date,
  Actual date,
  Firm name text,
  CONSTRAINT semi_production_pkey PRIMARY KEY (id)
);